# Generated by Django 5.0.2 on 2024-03-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_owner_user_user_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_owner',
            new_name='owner',
        ),
    ]
