# Generated by Django 5.0.2 on 2024-03-19 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_owner_user_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='owner',
            new_name='user_owner',
        ),
    ]
