# Generated by Django 5.0.2 on 2024-03-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lesson',
            field=models.ManyToManyField(related_name='course', to='materials.lesson', verbose_name='уроки'),
        ),
    ]
