# Generated by Django 5.0.2 on 2024-03-24 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_rename_user_owner_course_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('\\b[A-Za-z0-9._%+-]+@yourtube+\\.com\\b')], verbose_name='ссылка на видео'),
        ),
    ]
