# Generated by Django 5.0.2 on 2024-03-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_subscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscript',
            name='is_active_subscript',
            field=models.BooleanField(default=True, verbose_name='подписка'),
        ),
    ]
