# Generated by Django 5.0.2 on 2024-03-26 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_alter_subscript_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscript',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscript', to='materials.course', verbose_name='курс'),
        ),
    ]
